{
  "name": "FootballScores",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "DateTableTemplate_53b8b82f-ee89-48b2-a250-0f30e8c10312",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "d13062bf-5126-438c-84b6-0deb40845b57",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "dbdf5f44-2616-4a54-836a-393875f06f8f",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "02efaf04-ae87-4e6b-97be-71e9ca5e51c7",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "d753f1be-89f5-4cbb-98e3-2023ddf65ffc",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "4d3f21c1-5bc8-486e-b3e8-94b913d05327",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "91baf88b-90e8-4913-9067-ebe2d5bae6b1",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "d30e5a20-da96-419e-bd55-9d6fdad3d72f",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "4575c6b5-e339-408a-b6dc-e0520522dac7",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_53b8b82f-ee89-48b2-a250-0f30e8c10312-21a83130-4045-4a3d-97bf-5fac7fc2534c",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "3e24d271-4c17-4291-86b6-403c50e138d5",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "bc6864c1-5f0b-41b7-8d7a-5ab64a10e62d"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "968c8158-a8ca-4e02-a4c4-9bcba4973f7e"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "af65d288-e9aa-47f6-957b-3976fe481f67"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "9f6c0e0c-9f0f-432d-9d05-991481b20f66"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "2020-21",
        "lineageTag": "ad0e0579-6919-4b16-8e0d-c725553f7e38",
        "columns": [
          {
            "name": "Source.Name",
            "dataType": "string",
            "sourceColumn": "Source.Name",
            "lineageTag": "56c65edf-94f5-42fa-8634-6d8ef1cffcd0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Source.Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Round",
            "dataType": "int64",
            "sourceColumn": "Round",
            "formatString": "0",
            "lineageTag": "e4f76bf0-8919-4cf4-a4aa-f6bf308cbeed",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Round"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "851cb0af-b5a1-49f1-a645-d524ccce09af",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "fa6a6ff6-2371-49c5-8122-c392a4d1cb87",
                "defaultHierarchy": {
                  "table": "LocalDateTable_22c0f0a5-53d7-48bb-b5a0-298592332172",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"D\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Team 1",
            "dataType": "string",
            "sourceColumn": "Team 1",
            "lineageTag": "2b37e189-4324-4a57-8a1e-d06600e88ff5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Team 1"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "FT",
            "dataType": "string",
            "sourceColumn": "FT",
            "lineageTag": "b36617fb-e826-43be-937c-8f55691cc4e1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "FT"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Team 2",
            "dataType": "string",
            "sourceColumn": "Team 2",
            "lineageTag": "c2bb6aee-a0af-43b2-bb81-885e4b1169ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Team 2"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "2020-21-60045f2a-e85e-4b1e-b783-98d9057ffe4f",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\temp\\england-master\\2020s\\2020-21\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Round\", Int64.Type}, {\"Date\", type date}, {\"Team 1\", type text}, {\"FT\", type text}, {\"Team 2\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_22c0f0a5-53d7-48bb-b5a0-298592332172",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "1e71347f-a90e-4b19-a32f-880731fde264",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "5aa843b4-4f81-486d-9724-899564ce1edc",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "5ef55917-7310-4f27-b00e-2c9973617bbd",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "a4edc722-b596-4830-ab25-738a7cc36e40",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "49158d15-8948-400e-95e3-5dce8536a5e1",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "40ec30e0-2cd9-43ab-ac7f-fd7129a46a22",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "b70b39fe-5f1e-44b4-86b5-5cec008153a7",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "1cecf73d-1117-4fe5-861f-7436f4621ba8",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_22c0f0a5-53d7-48bb-b5a0-298592332172-503c79b0-49d7-4d03-9f22-6554c4d4f0b0",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('2020-21'[Date])), 1, 1), Date(Year(MAX('2020-21'[Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "ab830db2-9dd6-46d8-b44b-f83fd7b3e12f",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "800b6e82-68b2-4f16-a04a-2fd379a390ed"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "6c1b1c95-57eb-48b0-bf9f-344f1c32a47a"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "21aa9fee-1926-4925-9d5b-2d66775504a3"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "99aa7530-b727-4605-b3c2-06860cb528bc"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "fa6a6ff6-2371-49c5-8122-c392a4d1cb87",
        "fromTable": "2020-21",
        "fromColumn": "Date",
        "toTable": "LocalDateTable_22c0f0a5-53d7-48bb-b5a0-298592332172",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "expressions": [
      {
        "name": "Sample File",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\temp\\england-master\\2020s\\2020-21\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "queryGroup": "Transform File from 2020-21\\Helper Queries",
        "lineageTag": "4422b914-291b-472c-aff6-a5cb29fb635f",
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ]
      },
      {
        "name": "Parameter1",
        "kind": "m",
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "queryGroup": "Transform File from 2020-21\\Helper Queries",
        "lineageTag": "981898d0-128d-493c-86f8-160929580355",
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ]
      },
      {
        "name": "Transform Sample File",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "queryGroup": "Transform File from 2020-21",
        "lineageTag": "183c918a-89c5-4db1-8247-926e39578dbc",
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Transform File",
        "kind": "m",
        "expression": [
          "let",
          "    Source = (Parameter1) => let",
          "        Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "queryGroup": "Transform File from 2020-21\\Helper Queries",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "lineageTag": "92d947ad-0a31-4c9b-8232-f8f1058a8e0f",
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Transform File from 2020-21",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Transform File from 2020-21\\Helper Queries",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.100.684.0 (21.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"2020-21\",\"Sample File\",\"Parameter1\",\"Transform Sample File\",\"Transform File\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ]
  }
}